import type { CapabilityDefinition } from "../../capability/types"

export const credentialManifest: CapabilityDefinition = {
  id: "credential",
  name: "凭据",
  category: "CAPABILITY",
  provides: ["credential.save", "credential.get", "credential.delete"],
  dependsOn: ["bridge"],
  optionalDependencies: ["browser"],
  lifecycle: {
    supported: ["ACTIVE"],
    default: "ACTIVE",
    activatable: true,
    resident: true,
  },
  resources: {
    class: ["SECURITY_SENSITIVE"],
    suspendable: false,
    destroyable: false,
  },
  permissions: ["keyring.access"],
  persistence: { scope: "os_keyring", sensitive: true },
  entrypoint: "index.ts",
  semanticOwner: "KeyringStore",
  governanceStatus: "GOVERNED",
  status: "COMPATIBILITY_WRAPPED",
  v1: {
    id: "credential",
    version: "2.0.0",
    displayName: "凭据",
    description: "OS keyring 常驻安全能力。Runtime 只编排其存在性，不复制秘密、不支持 suspend/disable。",
    maturity: "C2",
    maturityEvidence: [
      "scripts/check-security-policy.py",
      "scripts/check-sensitive-side-effects.mjs",
      "scripts/check-native-capability-boundaries.mjs",
    ],
    dependencies: ["bridge"],
    optionalDependencies: ["browser"],
    conflicts: [],
    provides: ["credential.save", "credential.get", "credential.delete"],
    requires: [],
    contributions: [{ id: "credential.list", slot: "bookmark-credentials", type: "surface" }],
    permissions: ["keyring.access"],
    resources: [
      { kind: "KEYRING", ownership: "owned", evidence: "src-tauri/src/security_policy.rs" },
    ],
    persistenceScope: "os_keyring",
    persistenceSensitive: true,
    activationPolicy: "auto",
    deactivationPolicy: "resident",
    installPolicy: "static",
    uninstallPolicy: "static",
    hotPlug: {
      level: "HP0",
      enable: false,
      disable: false,
      register: false,
      unregister: false,
      install: false,
      uninstall: false,
      limitationReason: "Resident security capability: intentionally not hot-pluggable; B maturity is independent registration and contract ownership, not runtime disable.",
    },
    publicContract: [{ name: "publicApi", locator: "src/capabilities/credential/public.ts" }],
    entrypoint: "src/capabilities/credential/index.ts",
    semanticOwner: "KeyringStore",
  },
}
