import type { CapabilityDefinition } from "../../capability/types"

export const scriptManifest: CapabilityDefinition = {
  id: "script",
  name: "脚本",
  category: "CAPABILITY",
  provides: ["script.run", "script.snippet"],
  dependsOn: ["bridge"],
  optionalDependencies: [],
  lifecycle: {
    supported: ["ACTIVE"],
    default: "ACTIVE",
    activatable: true,
    resident: false,
  },
  resources: {
    class: ["PROCESS"],
    suspendable: false,
    destroyable: true,
  },
  permissions: ["process.spawn"],
  persistence: { scope: "disk", sensitive: false },
  entrypoint: "index.ts",
  semanticOwner: "useScriptStore",
  governanceStatus: "GOVERNED",
  status: "COMPATIBILITY_WRAPPED",
  v1: {
    id: "script",
    version: "2.0.0",
    displayName: "脚本",
    description: "脚本库 CRUD、参数化执行与运行历史；前端 owner/UI 独立于 Workspace，原生执行由 script capability 承载。",
    maturity: "C2",
    maturityEvidence: [
      "scripts/check-script-domain-policy.py",
      "scripts/check-script-exec-policy.py",
      "scripts/check-script-ui-logic.mjs",
      "scripts/check-script-ui-policy.py",
      "scripts/check-capability-contract-drift.mjs",
    ],
    dependencies: ["bridge"],
    optionalDependencies: [],
    conflicts: [],
    provides: ["script.run", "script.snippet"],
    requires: [],
    contributions: [{ id: "script.main.panel", slot: "workbench-main", type: "surface", view: "scripts" }],
    permissions: ["process.spawn"],
    resources: [
      { kind: "CHILD_PROCESS", ownership: "owned", evidence: "src-tauri/src/capabilities/script/script_runner.rs" },
    ],
    persistenceScope: "disk",
    persistenceSensitive: false,
    activationPolicy: "auto",
    deactivationPolicy: "graceful",
    installPolicy: "static",
    uninstallPolicy: "static",
    hotPlug: {
      level: "HP0",
      enable: false,
      disable: false,
      register: false,
      unregister: false,
      install: false,
      uninstall: false,
      limitationReason: "B maturity: independent module/owner/runtime registration established; child-process cancellation and hot-plug resource teardown remain explicitly unproven.",
    },
    publicContract: [{ name: "publicApi", locator: "src/capabilities/script/public.ts" }],
    entrypoint: "src/capabilities/script/index.ts",
    semanticOwner: "useScriptStore",
  },
}
