import type { CapabilityDefinition } from "../../capability/types"

export const sessionManifest: CapabilityDefinition = {
  id: "session",
  name: "会话",
  category: "CAPABILITY",
  provides: ["session.persist", "session.restore"],
  dependsOn: ["bridge"],
  optionalDependencies: [],
  lifecycle: {
    supported: ["ACTIVE"],
    default: "ACTIVE",
    activatable: true,
    resident: true,
  },
  resources: {
    class: ["LIGHT"],
    suspendable: false,
    destroyable: false,
  },
  permissions: ["fs.write"],
  persistence: { scope: "disk", sensitive: false },
  entrypoint: "index.ts",
  semanticOwner: "useSessionStore",
  governanceStatus: "GOVERNED",
  status: "COMPATIBILITY_WRAPPED",
  v1: {
    id: "session",
    version: "2.0.0",
    displayName: "会话",
    description: "历史会话持久化/恢复与关闭策略；前端 owner/UI 从 Browser 抽离，原生命令已位于 native session capability。",
    maturity: "C2",
    maturityEvidence: [
      "scripts/check-session-logic.mjs",
      "scripts/check-session-persistence-policy.py",
      "scripts/check-native-capability-boundaries.mjs",
    ],
    dependencies: ["bridge"],
    optionalDependencies: [],
    conflicts: [],
    provides: ["session.persist", "session.restore"],
    requires: [],
    contributions: [{ id: "session.dock", slot: "browser-dock", type: "surface", view: "session" }],
    permissions: ["fs.write"],
    resources: [
      { kind: "PERSISTENCE", ownership: "owned", evidence: "src-tauri/src/capabilities/session/commands.rs" },
    ],
    persistenceScope: "disk",
    persistenceSensitive: false,
    activationPolicy: "auto",
    deactivationPolicy: "resident",
    installPolicy: "static",
    uninstallPolicy: "static",
    hotPlug: {
      level: "HP0",
      enable: false,
      disable: false,
      register: false,
      unregister: false,
      install: false,
      uninstall: false,
      limitationReason: "Resident shutdown/persistence capability. Browser presentation is optional, but application shutdown ordering is intentionally not hot-pluggable.",
    },
    publicContract: [{ name: "publicApi", locator: "src/capabilities/session/public.ts" }],
    entrypoint: "src/capabilities/session/index.ts",
    semanticOwner: "useSessionStore",
  },
}
