<script setup lang="ts">
import { Copy, Download, RefreshCw, ChevronDown, ChevronUp } from '@lucide/vue';
import { useGridArchiveStore } from '../../capabilities/browser/public';
const archive = useGridArchiveStore();
</script>
<template>
<section class="grid-archive" aria-label="宫格回复归档">
  <div class="archive-toolbar"><select v-model="archive.mode" aria-label="提取范围" :disabled="archive.busy"><option value="latest">最新回复</option><option value="all">当前已加载回复</option></select><button :disabled="archive.busy || archive.saving" @click="archive.extract()"><Download :size="14"/>{{ archive.busy ? '提取中' : '提取回复' }}</button><button title="复制选中回复" :disabled="!archive.success.length || archive.busy" @click="archive.copy()"><Copy :size="14"/>复制</button><button :disabled="!archive.failed.length || archive.busy" @click="archive.extract(true)"><RefreshCw :size="14"/>重试失败项</button><span role="status">{{ archive.success.length }} 成功 · {{ archive.failed.length }} 失败</span><button title="归档详情" :aria-expanded="archive.expanded" @click="archive.expanded = !archive.expanded"><ChevronUp v-if="archive.expanded" :size="14"/><ChevronDown v-else :size="14"/></button></div>
  <div v-if="archive.expanded" class="archive-details"><div class="archive-save"><input v-model="archive.path" aria-label="Markdown 保存目录" placeholder="Markdown 保存目录"/><input v-model="archive.tags" aria-label="文件标签" placeholder="标签，用逗号分隔"/><button :disabled="archive.busy || archive.saving || !archive.path.trim() || !archive.success.length" @click="archive.save()"><Download :size="14"/>{{ archive.saving ? '保存中' : '分别保存 Markdown' }}</button></div><div class="archive-results"><label v-for="row in archive.rows" :key="row.index"><input v-model="row.selected" type="checkbox" :disabled="row.state !== 'ready' || archive.saving"/><strong>{{ row.label }}</strong><span>{{ row.saved ? '已保存' : row.state === 'ready' ? `${row.markdown.length} 字符` : row.state === 'reading' ? '提取中' : row.state === 'pending' ? '等待' : '失败' }}</span><small :title="row.saved">{{ row.error || row.saved }}</small></label></div><p v-if="archive.message" role="status">{{ archive.message }}</p></div>
</section>
</template>
<style scoped>
.grid-archive{flex:none;background:#f5f8f7;color:#263c37;border-bottom:1px solid #d7e0dc;font-size:12px}.archive-toolbar,.archive-save{display:flex;align-items:center;gap:8px;padding:4px 8px;flex-wrap:wrap}.grid-archive button{display:inline-flex;align-items:center;justify-content:center;gap:4px;background:#fff;color:inherit;border:1px solid #c4d1cb;border-radius:4px;padding:4px 8px;cursor:pointer}.grid-archive button:disabled{opacity:.45;cursor:default}.grid-archive input,.grid-archive select{padding:4px;border:1px solid #c4d1cb;border-radius:4px;min-width:0}.archive-save input:first-child{flex:1;min-width:180px}.archive-details{max-height:220px;overflow:auto}.archive-results{display:flex;flex-direction:column;padding:4px 10px}.archive-results label{display:flex;align-items:center;gap:8px;min-height:25px}.archive-results small{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;min-width:0}.archive-results strong{min-width:80px}.archive-results span{flex:none}.archive-details p{margin:4px 12px}
</style>
