import type { CapabilityDefinition } from "../../capability/types"

export const workbenchManifest: CapabilityDefinition = {
  id: "workbench",
  name: "工作台",
  category: "CAPABILITY",
  provides: ["workbench.navigation", "workbench.commands"],
  dependsOn: ["browser"],
  optionalDependencies: [],
  lifecycle: {
    supported: ["ACTIVE"],
    default: "ACTIVE",
    activatable: true,
    resident: true,
  },
  resources: {
    class: ["MEDIUM"],
    suspendable: false,
    destroyable: false,
  },
  permissions: [],
  persistence: { scope: "disk", sensitive: false },
  entrypoint: "index.ts",
  semanticOwner: "useWorkbenchStore",
  governanceStatus: "GOVERNED",
  status: "COMPATIBILITY_WRAPPED",
  v1: {
    id: "workbench",
    version: "2.0.0",
    displayName: "工作台",
    description: "Shell 工作台导航、折叠状态与统一命令入口；业务 owner/UI 归 capability，Shell 仅消费通用贡献槽。",
    maturity: "C2",
    maturityEvidence: [
      "scripts/check-workbench-logic.mjs",
      "scripts/check-workbench-ui.cjs",
      "scripts/check-contribution-registration.mjs",
    ],
    dependencies: ["browser"],
    optionalDependencies: [],
    conflicts: [],
    provides: ["workbench.navigation", "workbench.commands"],
    requires: [],
    contributions: [
      { id: "workbench.commands", slot: "commands", type: "surface" },
      { id: "workbench.rail", slot: "sidebar", type: "surface" },
    ],
    permissions: [],
    resources: [{ kind: "LAYOUT_STATE", ownership: "owned", evidence: "src/capabilities/workbench/state/useWorkbenchStore.ts" }],
    persistenceScope: "disk",
    persistenceSensitive: false,
    activationPolicy: "auto",
    deactivationPolicy: "resident",
    installPolicy: "static",
    uninstallPolicy: "static",
    hotPlug: {
      level: "HP0",
      enable: false,
      disable: false,
      register: false,
      unregister: false,
      install: false,
      uninstall: false,
      limitationReason: "Workbench is resident Shell structure. V2 isolates owner/UI/contributions but intentionally does not hot-unload the application frame.",
    },
    publicContract: [{ name: "publicApi", locator: "src/capabilities/workbench/public.ts" }],
    entrypoint: "src/capabilities/workbench/index.ts",
    semanticOwner: "useWorkbenchStore",
  },
}
