// GENERATED FILE. Run npm run generate:capability-registry.
import type { CapabilityManifestV1 } from './contract'
import { demoManifest as manifest0 } from './../../../packages/capability-demo/src/manifest'
import { agentManifest as manifest1 } from './../../capabilities/agent/manifest'
import { appsManifest as manifest2 } from './../../capabilities/apps/manifest'
import { bookmarkManifest as manifest3 } from './../../capabilities/bookmark/manifest'
import { browserManifest as manifest4 } from './../../capabilities/browser/manifest'
import { credentialManifest as manifest5 } from './../../capabilities/credential/manifest'
import { databaseManifest as manifest6 } from './../../capabilities/database/manifest'
import { gitManifest as manifest7 } from './../../capabilities/git/manifest'
import { graphManifest as manifest8 } from './../../capabilities/graph/manifest'
import { gridManifest as manifest9 } from './../../capabilities/grid/manifest'
import { homeManifest as manifest10 } from './../../capabilities/home/manifest'
import { pluginManifest as manifest11 } from './../../capabilities/plugin/manifest'
import { scriptManifest as manifest12 } from './../../capabilities/script/manifest'
import { sessionManifest as manifest13 } from './../../capabilities/session/manifest'
import { skillManifest as manifest14 } from './../../capabilities/skill/manifest'
import { taskManifest as manifest15 } from './../../capabilities/task/manifest'
import { terminalManifest as manifest16 } from './../../capabilities/terminal/manifest'
import { toolsManifest as manifest17 } from './../../capabilities/tools/manifest'
import { workbenchManifest as manifest18 } from './../../capabilities/workbench/manifest'
import { workspaceManifest as manifest19 } from './../../capabilities/workspace/manifest'
import { settingsManifest as manifest20 } from './../../settings/manifest'
import { clipboardManifest as manifest21 } from '@browser-os/capability-clipboard/manifest'
import { vaultManifest as manifest22 } from '@browser-os/capability-vault/manifest'
import { demoCapability as definition0 } from './../../../packages/capability-demo/src/index'
import { agentCapability as definition1 } from './../../capabilities/agent/index'
import { appsCapability as definition2 } from './../../capabilities/apps/index'
import { bookmarkCapability as definition3 } from './../../capabilities/bookmark/index'
import { browserCapability as definition4 } from './../../capabilities/browser/index'
import { credentialCapability as definition5 } from './../../capabilities/credential/index'
import { databaseCapability as definition6 } from './../../capabilities/database/index'
import { gitCapability as definition7 } from './../../capabilities/git/index'
import { graphCapability as definition8 } from './../../capabilities/graph/index'
import { gridCapability as definition9 } from './../../capabilities/grid/index'
import { homeCapability as definition10 } from './../../capabilities/home/index'
import { pluginCapability as definition11 } from './../../capabilities/plugin/index'
import { scriptCapability as definition12 } from './../../capabilities/script/index'
import { sessionCapability as definition13 } from './../../capabilities/session/index'
import { skillCapability as definition14 } from './../../capabilities/skill/index'
import { taskCapability as definition15 } from './../../capabilities/task/index'
import { terminalCapability as definition16 } from './../../capabilities/terminal/index'
import { toolsCapability as definition17 } from './../../capabilities/tools/index'
import { workbenchCapability as definition18 } from './../../capabilities/workbench/index'
import { workspaceCapability as definition19 } from './../../capabilities/workspace/index'
import { settingsCapability as definition20 } from './../../settings/index'

export const GENERATED_MANIFESTS: CapabilityManifestV1[] = [manifest0.v1 ?? manifest0, manifest1.v1 ?? manifest1, manifest2.v1 ?? manifest2, manifest3.v1 ?? manifest3, manifest4.v1 ?? manifest4, manifest5.v1 ?? manifest5, manifest6.v1 ?? manifest6, manifest7.v1 ?? manifest7, manifest8.v1 ?? manifest8, manifest9.v1 ?? manifest9, manifest10.v1 ?? manifest10, manifest11.v1 ?? manifest11, manifest12.v1 ?? manifest12, manifest13.v1 ?? manifest13, manifest14.v1 ?? manifest14, manifest15.v1 ?? manifest15, manifest16.v1 ?? manifest16, manifest17.v1 ?? manifest17, manifest18.v1 ?? manifest18, manifest19.v1 ?? manifest19, manifest20.v1 ?? manifest20, manifest21.v1 ?? manifest21, manifest22.v1 ?? manifest22]
export const GENERATED_MANIFEST_SOURCES = ["./../../../packages/capability-demo/src/manifest","./../../capabilities/agent/manifest","./../../capabilities/apps/manifest","./../../capabilities/bookmark/manifest","./../../capabilities/browser/manifest","./../../capabilities/credential/manifest","./../../capabilities/database/manifest","./../../capabilities/git/manifest","./../../capabilities/graph/manifest","./../../capabilities/grid/manifest","./../../capabilities/home/manifest","./../../capabilities/plugin/manifest","./../../capabilities/script/manifest","./../../capabilities/session/manifest","./../../capabilities/skill/manifest","./../../capabilities/task/manifest","./../../capabilities/terminal/manifest","./../../capabilities/tools/manifest","./../../capabilities/workbench/manifest","./../../capabilities/workspace/manifest","./../../settings/manifest","@browser-os/capability-clipboard/manifest","@browser-os/capability-vault/manifest"] as const
export const GENERATED_DEFINITIONS = { 'demo': definition0, 'agent': definition1, 'apps': definition2, 'bookmark': definition3, 'browser': definition4, 'credential': definition5, 'database': definition6, 'git': definition7, 'graph': definition8, 'grid': definition9, 'home': definition10, 'plugin': definition11, 'script': definition12, 'session': definition13, 'skill': definition14, 'task': definition15, 'terminal': definition16, 'tools': definition17, 'workbench': definition18, 'workspace': definition19, 'settings': definition20 } as const
